### ISSUE TITLE
extrascripts: before and after

### ISSUE THREAD

**Issue by jakub-g** [attester/attester#55]
It should be possible to inject `extraScripts` both before and after the framework itself.

The behavior supported up to 1.2.1 is to add extrascripts after AT.
The current behavior in master (not yet released) is to add them before AT, hence it breaks compatibility.

The syntax to support both scenarios could be like this:

```
 extraScripts:
   before:
    - foo.js
    - bar.js
   after:
    - quux.js
```

(extraScripts is an object, has "before" and/or "after" properties)

For backward compatibility, this has to be accepted as well:

```
 extraScripts:
  - foo.js
  - baz.js
```

(extraScripts is an array of strings) in which files are injected into `<HEAD>` _after_ the framework.
